Fixing Descartes not aborting on collision failure
tesseract-robotics/tesseract_planning pull request #452
Opened 2024-04-28 17:37 UTC by Jack-ReframeSystems

Two fixes here that I would like thoughts on. While testing some of our Descartes-based motions I noticed that the `context->isSuccessful` was returning `true` although the planner failed to build the LadderGraph because of collisions.

First fix is that the Descartes implementation is returning a failed BuildStatus from build that we aren't checking, so added the same check that is ran on an exception. That signals the failure but then we come to the abort not being done.

Second fix is making it so the MotionPlannerTask aborts when there is a failure... now this might be incorrect. Looking through `tesseract_task_graph` I saw there is `abort_terminals` but they don't exist for class types. How else are we supposed to have the Planning Tasks signal that they failed and fail out? This is the part I am confused about.

2024-05-07 21:11 UTC, Jack-ReframeSystems commented
@Levi-Armstrong thoughts on this?

2024-05-08 16:32 UTC, Levi-Armstrong requested changes

2024-05-09 00:52 UTC, Jack-ReframeSystems commented on tesseract_task_composer/planning/include/tesseract_task_composer/planning/nodes/motion_planner_task.hpp
> +    context.abort(uuid_);
Ok, that does solve for the actual failure of the motion planner when it should be failing, i.e. when checking `context->isSuccessful`. But, I presume I want to attach this `trigger_abort: true` field to the ErrorNode config. In which case, it eliminates the error message from the Descartes node and is just a generic "Error (Abort Triggered)" message.

Is there a way to pipe the error from the Descartes task into the Error task?

2024-05-14 14:25 UTC, Levi-Armstrong commented on tesseract_task_composer/planning/include/tesseract_task_composer/planning/nodes/motion_planner_task.hpp
> +    context.abort(uuid_);
I will have to think of a way to add this feature, but as alternative if you add the trigger abbort to the descartes_task you can get the uuid which triggered the abort and then lookup the task info using this uuid to get the data you want.

2024-05-29 18:59 UTC, Levi-Armstrong commented
Replaced by #457

2024-05-29 18:59 UTC, closed without merging

2024-05-29 19:00 UTC, Levi-Armstrong commented
@Jack-ReframeSystems Thanks for reporting the bug. I am still looking into a solution for how to propagate the error message.